#!/usr/bin/env python3
"""Generate Rust abstraction-duplication candidates without external dependencies.

This is a discovery tool, not a semantic proof system. It extracts a useful subset of
Rust items, computes structural/body similarity, and reports pairs that deserve manual
validation under the Rust Dup Unifier skill.
"""

from __future__ import annotations

import argparse
import bisect
import fnmatch
import hashlib
import json
import os
import re
import sys
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from difflib import SequenceMatcher
from pathlib import Path
from typing import Any, Iterable, Optional, Sequence

VERSION = "2.0.0"

IDENT = r"(?:r#)?[A-Za-z_][A-Za-z0-9_]*"
ITEM_RE = re.compile(
    rf"""
    (?:^[ \t]*|(?<=[{{}};])[ \t]*)
    (?P<prefix>
        (?:pub(?:[ \t]*\([^\n)]*\))?[ \t]+)?
        (?:(?:async|const|unsafe|default|auto)[ \t]+)*
        (?:extern(?:[ \t]+\"[^\"\n]*\")?[ \t]+)?
    )
    (?P<kind>struct|union|enum|trait|impl|fn|type|mod)\b
    """,
    re.MULTILINE | re.VERBOSE,
)

RUST_KEYWORDS = {
    "as",
    "async",
    "await",
    "break",
    "const",
    "continue",
    "crate",
    "dyn",
    "else",
    "enum",
    "extern",
    "false",
    "fn",
    "for",
    "if",
    "impl",
    "in",
    "let",
    "loop",
    "match",
    "mod",
    "move",
    "mut",
    "pub",
    "ref",
    "return",
    "self",
    "Self",
    "static",
    "struct",
    "super",
    "trait",
    "true",
    "type",
    "union",
    "unsafe",
    "use",
    "where",
    "while",
    "yield",
}

DEFAULT_EXCLUDED_DIRS = {
    ".git",
    ".hg",
    ".svn",
    ".cargo",
    "target",
    "node_modules",
    "vendor",
    "third_party",
    "dist",
}

TEST_PATH_SEGMENTS = {"tests", "test", "benches", "examples", "fixtures"}
GENERATED_HEADER_RE = re.compile(
    r"^\s*(?:\*\s*)?(?:this file (?:is|was) )?"
    r"(?:@generated|automatically generated|auto-generated|autogenerated|generated by|do not edit)\b",
    re.IGNORECASE | re.MULTILINE,
)
COMMON_METHOD_NAMES = {
    "new",
    "default",
    "clone",
    "fmt",
    "from",
    "into",
    "as_ref",
    "borrow",
    "deref",
    "drop",
    "build",
    "finish",
    "len",
    "is_empty",
}
TOKEN_RE = re.compile(
    r"::|->|=>|==|!=|<=|>=|&&|\|\||\+=|-=|\*=|/=|%=|<<|>>|\.\.|"
    r"(?:r#)?[A-Za-z_][A-Za-z0-9_]*|'[A-Za-z_][A-Za-z0-9_]*|"
    r"0x[0-9A-Fa-f_]+|0b[01_]+|0o[0-7_]+|\d[\d_]*(?:\.\d[\d_]*)?|[^\s]"
)


@dataclass
class RawItem:
    kind: str
    name: str
    file: str
    start: int
    end: int
    line: int
    header: str
    body: str
    raw_body: str
    body_start: Optional[int]
    body_end: Optional[int]
    visibility: str
    attributes: list[str]
    column: int = 1
    parent: Optional["RawItem"] = field(default=None, repr=False)
    impl_target: Optional[str] = None
    impl_target_name: Optional[str] = None
    impl_trait: Optional[str] = None


@dataclass
class Abstraction:
    kind: str
    name: str
    file: str
    line: int
    visibility: str
    attributes: list[str]
    column: int = 1
    members: dict[str, str] = field(default_factory=dict)
    methods: dict[str, str] = field(default_factory=dict)
    signature: str = ""
    body_tokens: list[str] = field(default_factory=list)
    calls: set[str] = field(default_factory=set)
    owner: Optional[str] = None
    metadata: dict[str, Any] = field(default_factory=dict)

    @property
    def anchor(self) -> str:
        return f"{self.file}:{self.line}"

    @property
    def stable_id(self) -> str:
        return f"{self.file}:{self.line}:{self.column}:{self.kind}:{self.name}"


@dataclass
class Candidate:
    left: Abstraction
    right: Abstraction
    score: float
    exact: bool
    signals: dict[str, float]
    divergences: list[str]
    rationale: list[str]

    @property
    def stable_id(self) -> str:
        return "DU-CAND-" + stable_hash("|".join(sorted((self.left.stable_id, self.right.stable_id))))

    @property
    def stream(self) -> str:
        return "callables" if self.left.kind in {"function", "method"} else "types"

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.stable_id,
            "stream": self.stream,
            "left": self.left.stable_id,
            "right": self.right.stable_id,
            "score": round(self.score, 4),
            "exact": self.exact,
            "signals": {k: round(v, 4) for k, v in sorted(self.signals.items())},
            "divergences": self.divergences,
            "rationale": self.rationale,
        }


def abstraction_summary(item: Abstraction) -> dict[str, Any]:
    return {
        "id": item.stable_id,
        "kind": item.kind,
        "name": item.name,
        "file": item.file,
        "line": item.line,
        "column": item.column,
        "visibility": item.visibility,
        "owner": item.owner,
        "attributes": item.attributes,
        "members": item.members,
        "methods": item.methods,
        "signature": item.signature,
        "body_token_count": len(item.body_tokens),
        "calls": sorted(item.calls),
        "metadata": item.metadata,
    }


def is_ident_char(ch: str) -> bool:
    return ch.isalnum() or ch == "_"


def _mask_range(out: list[str], text: str, start: int, end: int) -> None:
    for idx in range(start, min(end, len(out))):
        if text[idx] != "\n":
            out[idx] = " "


def _raw_string_prefix(text: str, i: int) -> Optional[tuple[int, int]]:
    """Return (quote_index, hash_count) when a raw string begins at i."""
    if i > 0 and is_ident_char(text[i - 1]):
        return None
    for prefix in ("br", "cr", "r"):
        if not text.startswith(prefix, i):
            continue
        j = i + len(prefix)
        hashes = 0
        while j < len(text) and text[j] == "#":
            hashes += 1
            j += 1
        if j < len(text) and text[j] == '"':
            return j, hashes
    return None


def _char_literal_end(text: str, i: int) -> Optional[int]:
    """Find a likely Rust char/byte-char literal end; lifetimes return None."""
    if text[i] != "'":
        return None
    match = re.match(r"'(?:[^'\\\n]|\\(?:u\{[0-9a-fA-F_]+\}|x[0-9a-fA-F]{2}|[^\n]))'", text[i:])
    return i + match.end() if match else None


def sanitize_rust(text: str, *, mask_literals: bool = True) -> str:
    """Mask comments and literals while preserving offsets and newlines."""
    out = list(text)
    i = 0
    n = len(text)
    while i < n:
        if text.startswith("//", i):
            end = text.find("\n", i + 2)
            if end == -1:
                end = n
            _mask_range(out, text, i, end)
            i = end
            continue

        if text.startswith("/*", i):
            depth = 1
            j = i + 2
            while j < n and depth:
                if text.startswith("/*", j):
                    depth += 1
                    j += 2
                elif text.startswith("*/", j):
                    depth -= 1
                    j += 2
                else:
                    j += 1
            _mask_range(out, text, i, j)
            i = j
            continue

        raw = _raw_string_prefix(text, i)
        if raw is not None:
            quote_idx, hashes = raw
            terminator = '"' + ("#" * hashes)
            end_at = text.find(terminator, quote_idx + 1)
            end = n if end_at == -1 else end_at + len(terminator)
            if mask_literals:
                _mask_range(out, text, i, end)
            i = end
            continue

        if text.startswith('b"', i) or text.startswith('c"', i):
            start = i
            j = i + 2
            escaped = False
            while j < n:
                ch = text[j]
                if escaped:
                    escaped = False
                elif ch == "\\":
                    escaped = True
                elif ch == '"':
                    j += 1
                    break
                j += 1
            if mask_literals:
                _mask_range(out, text, start, j)
            i = j
            continue

        if text[i] == '"':
            start = i
            j = i + 1
            escaped = False
            while j < n:
                ch = text[j]
                if escaped:
                    escaped = False
                elif ch == "\\":
                    escaped = True
                elif ch == '"':
                    j += 1
                    break
                j += 1
            if mask_literals:
                _mask_range(out, text, start, j)
            i = j
            continue

        if text.startswith("b'", i):
            end = _char_literal_end(text, i + 1)
            if end is not None:
                if mask_literals:
                    _mask_range(out, text, i, end)
                i = end
                continue

        if text[i] == "'":
            end = _char_literal_end(text, i)
            if end is not None:
                if mask_literals:
                    _mask_range(out, text, i, end)
                i = end
                continue

        i += 1

    return "".join(out)


def line_starts(text: str) -> list[int]:
    starts = [0]
    starts.extend(match.end() for match in re.finditer("\n", text))
    return starts


def line_number(starts: Sequence[int], offset: int) -> int:
    return bisect.bisect_right(starts, offset)


def find_matching(text: str, open_index: int, opening: str, closing: str) -> Optional[int]:
    depth = 0
    for idx in range(open_index, len(text)):
        ch = text[idx]
        if ch == opening:
            depth += 1
        elif ch == closing and not (closing == ">" and text[idx - 1:idx] == "-"):
            depth -= 1
            if depth == 0:
                return idx
    return None


def find_header_boundary(text: str, start: int) -> Optional[int]:
    paren = bracket = angle = 0
    i = start
    while i < len(text):
        ch = text[i]
        if ch == "(":
            paren += 1
        elif ch == ")":
            paren = max(0, paren - 1)
        elif ch == "[":
            bracket += 1
        elif ch == "]":
            bracket = max(0, bracket - 1)
        elif ch == "<":
            angle += 1
        elif ch == ">" and angle and text[i - 1:i] != "-":
            angle -= 1
        elif ch in "{;" and paren == 0 and bracket == 0 and angle == 0:
            return i
        i += 1
    return None


def split_top_level(text: str, delimiter: str = ",") -> list[str]:
    original = text
    text = sanitize_rust(text)
    expression = False
    parts: list[str] = []
    start = 0
    paren = bracket = brace = angle = 0
    i = 0
    while i < len(text):
        ch = text[i]
        if ch == "(":
            paren += 1
        elif ch == ")":
            paren = max(0, paren - 1)
        elif ch == "[":
            bracket += 1
        elif ch == "]":
            bracket = max(0, bracket - 1)
        elif ch == "{":
            brace += 1
        elif ch == "}":
            brace = max(0, brace - 1)
        elif ch == "=" and paren == bracket == brace == angle == 0:
            expression = True
        elif (
            ch == "<" and paren == bracket == brace == 0
            and (not expression or angle or text[:i].rstrip().endswith("::"))
        ):
            # Expressions use turbofish for generics; bare < and << are operators.
            angle += 1
        elif (
            ch == ">" and angle and paren == bracket == brace == 0
            and text[i - 1:i] != "-"
        ):
            # Nested groups shield both generic delimiters and shift operators.
            angle -= 1
        elif (
            ch == delimiter
            and paren == 0
            and bracket == 0
            and brace == 0
            and angle == 0
        ):
            parts.append(original[start:i])
            expression = False
            start = i + 1
        i += 1
    parts.append(original[start:])
    return parts


def find_top_level_char(text: str, target: str) -> Optional[int]:
    paren = bracket = brace = angle = 0
    for idx, ch in enumerate(text):
        if ch == "(":
            paren += 1
        elif ch == ")":
            paren = max(0, paren - 1)
        elif ch == "[":
            bracket += 1
        elif ch == "]":
            bracket = max(0, bracket - 1)
        elif ch == "{":
            brace += 1
        elif ch == "}":
            brace = max(0, brace - 1)
        elif ch == "<":
            angle += 1
        elif ch == ">" and angle and text[idx - 1:idx] != "-":
            angle -= 1
        elif ch == target and paren == bracket == brace == angle == 0:
            return idx
    return None


def normalize_text(text: str) -> str:
    text = re.sub(r"'[A-Za-z_][A-Za-z0-9_]*", "'L", text)
    text = re.sub(r"\s+", " ", text.strip())
    text = re.sub(r"\s*::\s*", "::", text)
    text = re.sub(r"\s*->\s*", "->", text)
    text = re.sub(r"\s*=>\s*", "=>", text)
    text = re.sub(r"\s*([,;:(){}\[\]<>=&*+!?|])\s*", r"\1", text)
    return text


def strip_attributes(segment: str) -> str:
    text = segment.lstrip()
    while text.startswith("#"):
        bracket = text.find("[")
        if bracket == -1:
            break
        end = find_matching(sanitize_rust(text), bracket, "[", "]")
        if end is None:
            break
        text = text[end + 1 :].lstrip()
    return text


def attribute_spans(text: str) -> list[tuple[int, int]]:
    spans = []
    cursor = 0
    for match in re.finditer(r"#\s*\[", text):
        if match.start() < cursor:
            continue
        end = find_matching(text, match.end() - 1, "[", "]")
        if end is not None:
            spans.append((match.start(), end + 1))
            cursor = end + 1
    return spans


def normalize_attribute_list(raw: str) -> list[str]:
    return sorted({raw[start:end].strip() for start, end in attribute_spans(sanitize_rust(raw))})


def collect_preceding_attributes(
    text: str, item_start: int, masked: Optional[str] = None,
    spans: Optional[list[tuple[int, int]]] = None,
) -> list[str]:
    masked = sanitize_rust(text) if masked is None else masked
    spans = attribute_spans(masked) if spans is None else spans
    attrs = []
    cursor = item_start
    position = bisect.bisect_right(spans, (item_start, len(text)))
    for start, end in reversed(spans[:position]):
        if end > cursor or masked[end:cursor].strip():
            break
        attrs.append(text[start:end].strip())
        cursor = start
    return sorted(set(attrs))


def mask_macros(text: str) -> str:
    out = list(text)
    cursor = 0
    # Macro bodies are token trees, not ordinary Rust item declarations.
    for match in re.finditer(rf"\b{IDENT}\s*!\s*(?:{IDENT}\s*)?([{{(\[])", text):
        if match.start() < cursor:
            continue
        opening = match.group(1)
        end = find_matching(text, match.end() - 1, opening, {"{": "}", "(": ")", "[": "]"}[opening])
        if end is not None:
            _mask_range(out, text, match.start(), end + 1)
            cursor = end + 1
    return "".join(out)


def item_name(kind: str, header: str) -> str:
    if kind == "impl":
        return "impl"
    match = re.search(rf"\b{re.escape(kind)}\s+({IDENT})", header)
    if not match:
        return "<anonymous>"
    return match.group(1).removeprefix("r#")


def visibility_from_prefix(prefix: str) -> str:
    match = re.search(r"\bpub(?:\s*\(([^)]*)\))?", prefix)
    if not match:
        return "private"
    if match.group(1):
        return f"pub({normalize_text(match.group(1))})"
    return "pub"


def remove_leading_generic_params(text: str) -> str:
    text = text.lstrip()
    if not text.startswith("<"):
        return text
    end = find_matching(text, 0, "<", ">")
    if end is None:
        return text
    return text[end + 1 :].lstrip()


def split_top_level_word(text: str, word: str) -> Optional[tuple[str, str]]:
    paren = bracket = brace = angle = 0
    for match in re.finditer(rf"\b{re.escape(word)}\b", text):
        idx = match.start()
        segment = text[:idx]
        paren = segment.count("(") - segment.count(")")
        bracket = segment.count("[") - segment.count("]")
        brace = segment.count("{") - segment.count("}")
        angle = segment.count("<") - segment.count(">")
        if paren == bracket == brace == angle == 0:
            return text[:idx], text[match.end() :]
    return None


def base_type_name(type_expr: str) -> Optional[str]:
    expr = type_expr.strip()
    if not expr or expr[0] in "[(*&!":
        return None
    expr = re.split(r"\bwhere\b", expr, maxsplit=1)[0].strip()
    prefix = expr.split("<", 1)[0].strip()
    identifiers = re.findall(IDENT, prefix)
    if not identifiers:
        return None
    candidate = identifiers[-1].removeprefix("r#")
    if candidate in {"dyn", "impl", "Self", "str"}:
        return None
    return candidate


def parse_impl_header(header: str) -> tuple[Optional[str], Optional[str], Optional[str]]:
    match = re.search(r"\bimpl\b", header)
    if not match:
        return None, None, None
    remainder = remove_leading_generic_params(header[match.end() :])
    where_split = split_top_level_word(remainder, "where")
    if where_split:
        remainder = where_split[0].strip()
    for_split = split_top_level_word(remainder, "for")
    if for_split:
        trait_expr = normalize_text(for_split[0])
        target_expr = normalize_text(for_split[1])
    else:
        trait_expr = None
        target_expr = normalize_text(remainder)
    return target_expr or None, base_type_name(target_expr), trait_expr or None


def parse_raw_items(text: str, rel_file: str) -> list[RawItem]:
    sanitized = sanitize_rust(text)
    extraction = mask_macros(sanitized)
    spans = attribute_spans(extraction)
    out = list(extraction)
    for start, end in spans:
        _mask_range(out, sanitized, start, end)
    masked = "".join(out)
    starts = line_starts(text)
    raw_items: list[RawItem] = []
    seen_starts: set[int] = set()

    header_end = 0
    for match in ITEM_RE.finditer(masked):
        keyword_start = match.start("kind")
        if keyword_start < header_end or keyword_start in seen_starts:
            continue
        boundary = find_header_boundary(sanitized, match.end("kind"))
        if boundary is None:
            continue
        header_end = boundary + 1
        terminator = sanitized[boundary]
        body_start: Optional[int] = None
        body_end: Optional[int] = None
        end = boundary + 1
        body = ""
        raw_body = ""
        if terminator == "{":
            close = find_matching(sanitized, boundary, "{", "}")
            if close is None:
                continue
            body_start = boundary
            body_end = close
            end = close + 1
            body = sanitized[boundary + 1 : close]
            raw_body = text[boundary + 1 : close]

        header = sanitize_rust(text[match.start("prefix") : boundary], mask_literals=False)
        kind = match.group("kind")
        name = item_name(kind, header)
        attrs = collect_preceding_attributes(text, match.start("prefix"), sanitized, spans)
        attrs = sorted(set(attrs))
        visibility = visibility_from_prefix(match.group("prefix") or "")
        impl_target = impl_target_name = impl_trait = None
        if kind == "impl":
            impl_target, impl_target_name, impl_trait = parse_impl_header(header)
            name = (
                f"{impl_trait} for {impl_target}"
                if impl_trait and impl_target
                else impl_target or "impl"
            )

        if name == "<anonymous>":
            continue
        raw_items.append(
            RawItem(
                kind=kind,
                name=name,
                file=rel_file,
                start=match.start("prefix"),
                end=end,
                line=line_number(starts, keyword_start),
                column=keyword_start - starts[line_number(starts, keyword_start) - 1] + 1,
                header=header,
                body=body,
                raw_body=raw_body,
                body_start=body_start,
                body_end=body_end,
                visibility=visibility,
                attributes=attrs,
                impl_target=impl_target,
                impl_target_name=impl_target_name,
                impl_trait=impl_trait,
            )
        )
        seen_starts.add(keyword_start)

    raw_items.sort(key=lambda item: (item.start, -(item.end - item.start)))
    stack: list[RawItem] = []
    for item in raw_items:
        while stack and (stack[-1].body_end is None or item.start > stack[-1].body_end):
            stack.pop()
        parent = None
        for possible in reversed(stack):
            if (
                possible.body_start is not None
                and possible.body_end is not None
                and possible.body_start < item.start < possible.body_end
            ):
                parent = possible
                break
        item.parent = parent
        if item.body_start is not None and item.body_end is not None:
            stack.append(item)

    return raw_items


def parse_struct_fields(body: str, tuple_body: Optional[str] = None) -> dict[str, str]:
    fields: dict[str, str] = {}
    source = sanitize_rust(tuple_body if tuple_body is not None else body, mask_literals=False)
    for index, raw_segment in enumerate(split_top_level(source)):
        segment = strip_attributes(raw_segment).strip()
        if not segment:
            continue
        segment = re.sub(r"^pub(?:\s*\([^)]*\))?\s+", "", segment).strip()
        colon = find_top_level_char(segment, ":")
        if tuple_body is not None or colon is None:
            fields[str(index)] = normalize_text(segment)
            continue
        left = segment[:colon].strip()
        right = segment[colon + 1 :].strip()
        names = re.findall(IDENT, left)
        if names:
            fields[names[-1].removeprefix("r#")] = normalize_text(right)
    return fields


def parse_enum_variants(body: str) -> dict[str, str]:
    variants: dict[str, str] = {}
    for raw_segment in split_top_level(sanitize_rust(body, mask_literals=False)):
        segment = strip_attributes(raw_segment).strip()
        if not segment:
            continue
        match = re.match(rf"({IDENT})\b(.*)", segment, flags=re.S)
        if not match:
            continue
        name = match.group(1).removeprefix("r#")
        rest = match.group(2).strip()
        if not rest:
            payload = "unit"
        elif rest.startswith("("):
            end = find_matching(rest, 0, "(", ")")
            inner = rest[1:end] if end is not None else rest[1:]
            payload = "tuple(" + ",".join(normalize_text(x) for x in split_top_level(inner) if x.strip()) + ")"
        elif rest.startswith("{"):
            end = find_matching(rest, 0, "{", "}")
            inner = rest[1:end] if end is not None else rest[1:]
            fields = parse_struct_fields(inner)
            payload = "struct{" + ",".join(f"{k}:{v}" for k, v in sorted(fields.items())) + "}"
        elif rest.startswith("="):
            payload = "discriminant=" + normalize_text(rest[1:])
        else:
            payload = normalize_text(rest)
        variants[name] = payload
    return variants


def type_alias_target(header: str) -> str:
    eq = find_top_level_char(header, "=")
    if eq is None:
        return ""
    return normalize_text(header[eq + 1 :])


def function_signature_shape(header: str, function_name: str) -> str:
    signature = normalize_text(header)
    signature = re.sub(
        rf"\bfn\s+{re.escape(function_name)}\b",
        "fn $name",
        signature,
        count=1,
    )

    open_paren = signature.find("(")
    if open_paren == -1:
        return signature
    close_paren = find_matching(signature, open_paren, "(", ")")
    if close_paren is None:
        return signature

    params = signature[open_paren + 1 : close_paren]
    shaped: list[str] = []
    for raw_param in split_top_level(params):
        param = raw_param.strip()
        if not param:
            continue
        if re.fullmatch(r"(?:&(?:'L)?(?:mut)?)?self", param.replace(" ", "")):
            shaped.append(normalize_text(param))
            continue
        colon = find_top_level_char(param, ":")
        if colon is not None:
            shaped.append("_:" + normalize_text(param[colon + 1 :]))
        else:
            shaped.append(normalize_text(param))
    return signature[: open_paren + 1] + ",".join(shaped) + signature[close_paren:]


def extract_literals(text: str) -> list[str]:
    """Extract normalized literal values while skipping comments."""
    literals: list[str] = []
    i = 0
    n = len(text)
    number_re = re.compile(r"0x[0-9A-Fa-f_]+|0b[01_]+|0o[0-7_]+|\d[\d_]*(?:\.\d[\d_]*)?(?:[A-Za-z][A-Za-z0-9_]*)?")
    while i < n:
        if text.startswith("//", i):
            end = text.find("\n", i + 2)
            i = n if end == -1 else end
            continue
        if text.startswith("/*", i):
            depth = 1
            j = i + 2
            while j < n and depth:
                if text.startswith("/*", j):
                    depth += 1
                    j += 2
                elif text.startswith("*/", j):
                    depth -= 1
                    j += 2
                else:
                    j += 1
            i = j
            continue

        raw = _raw_string_prefix(text, i)
        if raw is not None:
            quote_idx, hashes = raw
            terminator = '"' + ("#" * hashes)
            end_at = text.find(terminator, quote_idx + 1)
            if end_at == -1:
                content = text[quote_idx + 1 :]
                i = n
            else:
                content = text[quote_idx + 1 : end_at]
                i = end_at + len(terminator)
            literals.append("str:" + content)
            continue

        prefix_len = 0
        literal_kind = "str"
        if text.startswith('b"', i):
            prefix_len = 1
            literal_kind = "bytes"
        elif text.startswith('c"', i):
            prefix_len = 1
            literal_kind = "cstr"
        elif text[i] == '"':
            prefix_len = 0
            literal_kind = "str"
        if text[i] == '"' or prefix_len:
            quote_idx = i + prefix_len
            j = quote_idx + 1
            escaped = False
            while j < n:
                ch = text[j]
                if escaped:
                    escaped = False
                elif ch == "\\":
                    escaped = True
                elif ch == '"':
                    break
                j += 1
            content = text[quote_idx + 1 : j]
            literals.append(literal_kind + ":" + content)
            i = min(n, j + 1)
            continue

        if text.startswith("b'", i):
            end = _char_literal_end(text, i + 1)
            if end is not None:
                literals.append("byte_char:" + text[i + 2 : end - 1])
                i = end
                continue
        if text[i] == "'":
            end = _char_literal_end(text, i)
            if end is not None:
                literals.append("char:" + text[i + 1 : end - 1])
                i = end
                continue

        if text[i].isdigit() and (i == 0 or not is_ident_char(text[i - 1])):
            match = number_re.match(text, i)
            if match:
                literals.append("num:" + match.group(0))
                i = match.end()
                continue
        i += 1
    return literals


def body_tokens(body: str) -> list[str]:
    raw = TOKEN_RE.findall(body)
    normalized: list[str] = []
    for idx, token in enumerate(raw):
        if re.fullmatch(r"0x[0-9A-Fa-f_]+|0b[01_]+|0o[0-7_]+|\d[\d_]*(?:\.\d[\d_]*)?", token):
            normalized.append("NUM")
            continue
        if re.fullmatch(IDENT, token):
            ident = token.removeprefix("r#")
            previous = raw[idx - 1] if idx else ""
            following = raw[idx + 1] if idx + 1 < len(raw) else ""
            if ident in RUST_KEYWORDS:
                normalized.append(ident)
            elif previous in {".", "::"} or following == "!":
                normalized.append(ident)
            elif ident[:1].isupper():
                normalized.append("TYPE")
            else:
                normalized.append("ID")
            continue
        if token.startswith("'"):
            normalized.append("'L")
            continue
        normalized.append(token)
    return normalized


def extract_calls(body: str) -> set[str]:
    tokens = TOKEN_RE.findall(body)
    calls: set[str] = set()
    for idx, token in enumerate(tokens):
        if not re.fullmatch(IDENT, token):
            continue
        ident = token.removeprefix("r#")
        previous = tokens[idx - 1] if idx else ""
        following = tokens[idx + 1] if idx + 1 < len(tokens) else ""
        after = tokens[idx + 2] if idx + 2 < len(tokens) else ""
        if previous in {".", "::"}:
            calls.add(ident)
        elif following == "!":
            calls.add(ident + "!")
        elif following == "(" and ident not in RUST_KEYWORDS:
            calls.add(ident)
        elif following == "::" and after:
            calls.add(ident + "::" + after.removeprefix("r#"))
    return calls


def direct_assoc_consts(body: str) -> dict[str, str]:
    result: dict[str, str] = {}
    depth = 0
    line_start = 0
    for idx, ch in enumerate(body + "\n"):
        if ch == "{" and idx >= line_start:
            depth += 1
        elif ch == "}" and idx >= line_start:
            depth = max(0, depth - 1)
        elif ch == "\n":
            line = body[line_start:idx]
            if depth == 0:
                match = re.match(
                    rf"\s*(?:pub(?:\s*\([^)]*\))?\s+)?const\s+({IDENT})\s*:\s*(.*?)(?:=|;|$)",
                    line,
                )
                if match:
                    result["const " + match.group(1).removeprefix("r#")] = normalize_text(match.group(2))
            line_start = idx + 1
    return result


def tuple_struct_inner(header: str, name: str) -> Optional[str]:
    name_match = re.search(rf"\b(?:struct|union)\s+{re.escape(name)}\b", header)
    if not name_match:
        return None
    tail = remove_leading_generic_params(header[name_match.end():])
    if not tail.startswith("("):
        return None
    close_paren = find_matching(sanitize_rust(tail), 0, "(", ")")
    return tail[1:close_paren] if close_paren is not None else None


def member_contracts(source: str, *, positional: bool = False) -> dict[str, Any]:
    contracts = {}
    source = sanitize_rust(source, mask_literals=False)
    for index, segment in enumerate(split_top_level(source)):
        rest = strip_attributes(segment)
        if not rest.strip():
            continue
        visibility = visibility_from_prefix(rest)
        rest = re.sub(r"^pub(?:\s*\([^)]*\))?\s+", "", rest)
        name = re.match(IDENT, rest)
        if positional or name:
            key = str(index) if positional else name.group().removeprefix("r#")
            prefix_length = len(segment) - len(strip_attributes(segment))
            contracts[key] = {"visibility": visibility, "attributes": normalize_attribute_list(segment[:prefix_length])}
    return contracts


def build_abstractions(raw_items: list[RawItem]) -> list[Abstraction]:
    abstractions: list[Abstraction] = []
    method_records: list[tuple[RawItem, Abstraction]] = []
    raw_to_abstraction: dict[int, Abstraction] = {}

    for raw in raw_items:
        if raw.parent and raw.parent.kind == "fn":
            continue

        if raw.kind in {"struct", "union"}:
            tuple_inner = tuple_struct_inner(raw.header, raw.name)
            members = parse_struct_fields(raw.raw_body, tuple_inner)
            abstraction = Abstraction(
                kind=raw.kind,
                name=raw.name,
                file=raw.file,
                line=raw.line,
                visibility=raw.visibility,
                attributes=raw.attributes,
                members=members,
                metadata={
                    "shape": "tuple" if tuple_inner is not None else "record",
                    "member_contracts": member_contracts(tuple_inner if tuple_inner is not None else raw.raw_body, positional=tuple_inner is not None),
                },
            )
        elif raw.kind == "enum":
            abstraction = Abstraction(
                kind="enum",
                name=raw.name,
                file=raw.file,
                line=raw.line,
                visibility=raw.visibility,
                attributes=raw.attributes,
                members=parse_enum_variants(raw.raw_body),
                metadata={"member_contracts": member_contracts(raw.raw_body)},
            )
        elif raw.kind == "trait":
            abstraction = Abstraction(
                kind="trait",
                name=raw.name,
                file=raw.file,
                line=raw.line,
                visibility=raw.visibility,
                attributes=raw.attributes,
                members=direct_assoc_consts(raw.body),
                signature=normalize_text(re.sub(rf"\btrait\s+{re.escape(raw.name)}\b", "trait $name", raw.header, count=1)),
            )
        elif raw.kind == "type" and not (raw.parent and raw.parent.kind in {"trait", "impl"}):
            target = type_alias_target(raw.header)
            abstraction = Abstraction(
                kind="type_alias",
                name=raw.name,
                file=raw.file,
                line=raw.line,
                visibility=raw.visibility,
                attributes=raw.attributes,
                members={"target": target} if target else {},
                signature=normalize_text(raw.header),
            )
        elif raw.kind == "fn":
            parent = raw.parent
            if parent and parent.kind not in {"impl", "trait", "mod"}:
                continue
            if parent and parent.kind == "impl":
                owner = parent.impl_target or parent.name
                display_name = f"{owner}::{raw.name}"
                metadata = {
                    "impl_trait": parent.impl_trait,
                    "impl_target": parent.impl_target,
                    "impl_target_name": parent.impl_target_name,
                }
                kind = "method"
            elif parent and parent.kind == "trait":
                owner = parent.name
                display_name = f"{owner}::{raw.name}"
                metadata = {"trait_default_method": bool(raw.body)}
                kind = "method"
            else:
                owner = None
                display_name = raw.name
                metadata = {}
                kind = "function"
            abstraction = Abstraction(
                kind=kind,
                name=display_name,
                file=raw.file,
                line=raw.line,
                visibility=raw.visibility,
                attributes=raw.attributes,
                signature=function_signature_shape(raw.header, raw.name),
                body_tokens=body_tokens(raw.body),
                calls=extract_calls(raw.body),
                owner=owner,
                metadata=metadata | {"method_name": raw.name, "literals": extract_literals(raw.raw_body)},
            )
            method_records.append((raw, abstraction))
        else:
            continue

        abstraction.column = raw.column
        abstractions.append(abstraction)
        raw_to_abstraction[id(raw)] = abstraction

    # Attach direct trait members.
    for raw, method in method_records:
        parent = raw.parent
        if not parent or parent.kind != "trait":
            continue
        trait = raw_to_abstraction.get(id(parent))
        if trait:
            trait.methods[raw.name] = method.signature

    for raw in raw_items:
        if raw.kind != "type" or not raw.parent or raw.parent.kind != "trait":
            continue
        trait = raw_to_abstraction.get(id(raw.parent))
        if trait:
            trait.members["type " + raw.name] = type_alias_target(raw.header) or normalize_text(raw.header)

    # Attach inherent methods to the most plausible nominal type.
    nominal_types = [item for item in abstractions if item.kind in {"struct", "union", "enum"}]
    by_file_and_name: dict[tuple[str, str], list[Abstraction]] = defaultdict(list)
    by_name: dict[str, list[Abstraction]] = defaultdict(list)
    for item in nominal_types:
        by_file_and_name[(item.file, item.name)].append(item)
        by_name[item.name].append(item)

    for raw, method in method_records:
        parent = raw.parent
        if not parent or parent.kind != "impl" or parent.impl_trait:
            continue
        target_name = parent.impl_target_name
        if not target_name:
            continue
        matches = by_file_and_name.get((raw.file, target_name), [])
        if not matches and len(by_name.get(target_name, [])) == 1:
            matches = by_name[target_name]
        if len(matches) == 1:
            matches[0].methods[raw.name] = method.signature

    return abstractions


def name_words(name: str) -> list[str]:
    leaf = name.split("::")[-1]
    leaf = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", leaf)
    return [part.lower() for part in re.split(r"[^A-Za-z0-9]+", leaf) if part]


def jaccard(left: Iterable[str], right: Iterable[str]) -> float:
    a = set(left)
    b = set(right)
    if not a and not b:
        return 1.0
    if not a or not b:
        return 0.0
    return len(a & b) / len(a | b)


def sequence_similarity(left: str, right: str) -> float:
    if not left and not right:
        return 1.0
    if not left or not right:
        return 0.0
    return SequenceMatcher(None, left, right).ratio()


def name_similarity(left: str, right: str) -> float:
    a_words = name_words(left)
    b_words = name_words(right)
    sequence = sequence_similarity("_".join(a_words), "_".join(b_words))
    word_overlap = jaccard(a_words, b_words)
    return max(sequence, word_overlap)


def average_mapping_similarity(
    left: dict[str, str], right: dict[str, str], shared_keys: set[str]
) -> float:
    if not shared_keys:
        return 0.0
    return sum(sequence_similarity(left[key], right[key]) for key in shared_keys) / len(shared_keys)


def token_shingles(tokens: Sequence[str], size: int = 5) -> set[tuple[str, ...]]:
    if not tokens:
        return set()
    if len(tokens) < size:
        return {tuple(tokens)}
    return {tuple(tokens[idx : idx + size]) for idx in range(len(tokens) - size + 1)}


def weighted_score(parts: Sequence[tuple[float, float]]) -> float:
    effective = [(value, weight) for value, weight in parts if weight > 0]
    total = sum(weight for _, weight in effective)
    if total == 0:
        return 0.0
    return sum(value * weight for value, weight in effective) / total


def format_set(values: Iterable[str], limit: int = 8) -> str:
    items = sorted(values)
    if len(items) > limit:
        return ", ".join(items[:limit]) + f", … (+{len(items) - limit})"
    return ", ".join(items)


def compare_nominal(left: Abstraction, right: Abstraction) -> Optional[Candidate]:
    left_names = set(left.members)
    right_names = set(right.members)
    shared = left_names & right_names
    named_members = {name for name in left_names | right_names if not name.isdigit()}
    member_name_overlap = jaccard(left_names & named_members, right_names & named_members) if named_members else 0.0
    member_shape = average_mapping_similarity(left.members, right.members, shared)
    type_multiset = jaccard(left.members.values(), right.members.values())
    method_names = jaccard(left.methods, right.methods)
    shared_methods = set(left.methods) & set(right.methods)
    method_shape = average_mapping_similarity(left.methods, right.methods, shared_methods)
    names = name_similarity(left.name, right.name)

    if (left.metadata.get("shape") == "tuple" or right.metadata.get("shape") == "tuple") and min(len(left_names), len(right_names)) <= 1:
        return None
    if len(left_names | right_names) < 2 and len(set(left.methods) | set(right.methods)) < 2:
        return None
    if member_name_overlap < 0.25 and type_multiset < 0.45 and method_names < 0.5:
        return None

    score = weighted_score(
        [
            (member_name_overlap, 0.42 if named_members else 0.0),
            (member_shape, 0.24 if shared else 0.0),
            (type_multiset, 0.10),
            (method_names, 0.10 if left.methods or right.methods else 0.0),
            (method_shape, 0.08 if shared_methods else 0.0),
            (names, 0.06),
        ]
    )

    divergences: list[str] = []
    only_left = left_names - right_names
    only_right = right_names - left_names
    changed = sorted(key for key in shared if left.members[key] != right.members[key])
    if only_left:
        divergences.append(f"Only {left.name}: {format_set(only_left)}")
    if only_right:
        divergences.append(f"Only {right.name}: {format_set(only_right)}")
    if changed:
        details = "; ".join(
            f"{key}: {left.members[key]} ↔ {right.members[key]}" for key in changed[:6]
        )
        if len(changed) > 6:
            details += f"; … (+{len(changed) - 6})"
        divergences.append("Changed member shapes: " + details)

    only_left_methods = set(left.methods) - set(right.methods)
    only_right_methods = set(right.methods) - set(left.methods)
    changed_methods = sorted(
        key for key in shared_methods if left.methods[key] != right.methods[key]
    )
    if only_left_methods:
        divergences.append(f"Methods only on {left.name}: {format_set(only_left_methods)}")
    if only_right_methods:
        divergences.append(f"Methods only on {right.name}: {format_set(only_right_methods)}")
    if changed_methods:
        divergences.append("Changed method signatures: " + format_set(changed_methods))
    if left.attributes != right.attributes:
        divergences.append(
            "Attributes differ: "
            + f"{left.name}={left.attributes or ['none']} ↔ {right.name}={right.attributes or ['none']}"
        )

    exact = (
        left.members == right.members
        and left.methods == right.methods
        and left.attributes == right.attributes
        and left.visibility == right.visibility
    )
    rationale = []
    if member_name_overlap >= 0.7:
        rationale.append("strong member-name overlap")
    if member_shape >= 0.8 and shared:
        rationale.append("shared members have similar types or payloads")
    if method_names >= 0.7 and (left.methods or right.methods):
        rationale.append("similar inherent method surface")
    if type_multiset >= 0.7:
        rationale.append("similar member-type multiset")

    return Candidate(
        left=left,
        right=right,
        score=score,
        exact=exact,
        signals={
            "member_name_overlap": member_name_overlap,
            "shared_member_shape": member_shape,
            "member_type_overlap": type_multiset,
            "method_name_overlap": method_names,
            "shared_method_shape": method_shape,
            "name_similarity": names,
        },
        divergences=divergences or ["No mechanical divergence found."],
        rationale=rationale or ["combined structural similarity"],
    )


def compare_traits(left: Abstraction, right: Abstraction) -> Optional[Candidate]:
    method_overlap = jaccard(left.methods, right.methods)
    shared_methods = set(left.methods) & set(right.methods)
    method_shape = average_mapping_similarity(left.methods, right.methods, shared_methods)
    assoc_overlap = jaccard(left.members, right.members)
    shared_assoc = set(left.members) & set(right.members)
    assoc_shape = average_mapping_similarity(left.members, right.members, shared_assoc)
    names = name_similarity(left.name, right.name)

    total_members = len(set(left.methods) | set(right.methods) | set(left.members) | set(right.members))
    if total_members < 2:
        return None
    if method_overlap < 0.3 and assoc_overlap < 0.5:
        return None

    score = weighted_score(
        [
            (method_overlap, 0.46),
            (method_shape, 0.30 if shared_methods else 0.0),
            (assoc_overlap, 0.10 if left.members or right.members else 0.0),
            (assoc_shape, 0.06 if shared_assoc else 0.0),
            (names, 0.08),
        ]
    )

    divergences: list[str] = []
    only_left = set(left.methods) - set(right.methods)
    only_right = set(right.methods) - set(left.methods)
    changed = sorted(key for key in shared_methods if left.methods[key] != right.methods[key])
    if only_left:
        divergences.append(f"Methods only on {left.name}: {format_set(only_left)}")
    if only_right:
        divergences.append(f"Methods only on {right.name}: {format_set(only_right)}")
    if changed:
        divergences.append("Changed shared method signatures: " + format_set(changed))
    if left.members != right.members:
        divergences.append(
            f"Associated items differ: {left.name}={sorted(left.members)} ↔ {right.name}={sorted(right.members)}"
        )
    if left.attributes != right.attributes:
        divergences.append("Trait attributes differ.")

    exact = (
        left.methods == right.methods
        and left.members == right.members
        and left.attributes == right.attributes
        and left.visibility == right.visibility
    )
    rationale = []
    if method_overlap >= 0.7:
        rationale.append("strong required-method overlap")
    if method_shape >= 0.8 and shared_methods:
        rationale.append("shared methods have similar signatures")
    if assoc_overlap >= 0.7 and (left.members or right.members):
        rationale.append("similar associated-item surface")

    return Candidate(
        left=left,
        right=right,
        score=score,
        exact=exact,
        signals={
            "method_name_overlap": method_overlap,
            "shared_method_shape": method_shape,
            "associated_item_overlap": assoc_overlap,
            "shared_associated_item_shape": assoc_shape,
            "name_similarity": names,
        },
        divergences=divergences or ["No mechanical divergence found."],
        rationale=rationale or ["combined trait-surface similarity"],
    )


def compare_type_aliases(left: Abstraction, right: Abstraction) -> Optional[Candidate]:
    left_target = left.members.get("target", "")
    right_target = right.members.get("target", "")
    target_similarity = sequence_similarity(left_target, right_target)
    names = name_similarity(left.name, right.name)
    if target_similarity < 0.65:
        return None
    score = 0.85 * target_similarity + 0.15 * names
    exact = left_target == right_target and left.visibility == right.visibility
    divergences = []
    if left_target != right_target:
        divergences.append(f"Targets differ: {left_target} ↔ {right_target}")
    if left.visibility != right.visibility:
        divergences.append(f"Visibility differs: {left.visibility} ↔ {right.visibility}")
    return Candidate(
        left=left,
        right=right,
        score=score,
        exact=exact,
        signals={"target_similarity": target_similarity, "name_similarity": names},
        divergences=divergences or ["No mechanical divergence found."],
        rationale=["similar alias targets"],
    )


def compare_callables(left: Abstraction, right: Abstraction) -> Optional[Candidate]:
    if not left.body_tokens or not right.body_tokens:
        return None
    shorter = min(len(left.body_tokens), len(right.body_tokens))
    longer = max(len(left.body_tokens), len(right.body_tokens))
    if shorter < 10 or shorter / longer < 0.45:
        return None

    body_overlap = jaccard(token_shingles(left.body_tokens), token_shingles(right.body_tokens))
    signature = sequence_similarity(left.signature, right.signature)
    call_overlap = jaccard(left.calls, right.calls)
    left_literals = left.metadata.get("literals", [])
    right_literals = right.metadata.get("literals", [])
    literal_overlap = jaccard(left_literals, right_literals)
    names = name_similarity(left.metadata.get("method_name", left.name), right.metadata.get("method_name", right.name))
    score = weighted_score(
        [
            (body_overlap, 0.50),
            (signature, 0.24),
            (call_overlap, 0.15 if left.calls or right.calls else 0.0),
            (literal_overlap, 0.08 if left_literals or right_literals else 0.0),
            (names, 0.08),
        ]
    )

    left_method = left.metadata.get("method_name", left.name)
    right_method = right.metadata.get("method_name", right.name)
    if (
        left_method == right_method
        and left_method in COMMON_METHOD_NAMES
        and body_overlap < 0.65
    ):
        return None
    if shorter <= 20 and body_overlap < 0.80:
        return None
    if body_overlap < 0.35 and score < 0.75:
        return None

    divergences: list[str] = []
    if left.signature != right.signature:
        divergences.append(f"Signature shapes differ: {left.signature} ↔ {right.signature}")
    only_left_calls = left.calls - right.calls
    only_right_calls = right.calls - left.calls
    if only_left_calls:
        divergences.append(f"Calls only in {left.name}: {format_set(only_left_calls)}")
    if only_right_calls:
        divergences.append(f"Calls only in {right.name}: {format_set(only_right_calls)}")
    if left_literals != right_literals:
        divergences.append(
            f"Literals differ: {format_set(left_literals)} ↔ {format_set(right_literals)}"
        )
    if left.body_tokens != right.body_tokens:
        divergences.append(
            f"Body shapes differ: {len(left.body_tokens)} vs {len(right.body_tokens)} normalized tokens; "
            f"shingle overlap {body_overlap:.0%}."
        )

    exact = (
        left.signature == right.signature
        and left.body_tokens == right.body_tokens
        and left_literals == right_literals
    )
    rationale = []
    if body_overlap >= 0.7:
        rationale.append("strong normalized-body overlap")
    if signature >= 0.8:
        rationale.append("similar callable signature shape")
    if call_overlap >= 0.7 and (left.calls or right.calls):
        rationale.append("similar call surface")

    return Candidate(
        left=left,
        right=right,
        score=score,
        exact=exact,
        signals={
            "body_shingle_overlap": body_overlap,
            "signature_similarity": signature,
            "call_overlap": call_overlap,
            "literal_overlap": literal_overlap,
            "name_similarity": names,
        },
        divergences=divergences or ["No mechanical divergence found."],
        rationale=rationale or ["combined callable similarity"],
    )


def compare_pair(left: Abstraction, right: Abstraction) -> Optional[Candidate]:
    callable_kinds = {"function", "method"}
    if left.kind in callable_kinds and right.kind in callable_kinds:
        candidate = compare_callables(left, right)
    elif left.kind != right.kind:
        return None
    elif left.kind in {"struct", "union", "enum"}:
        candidate = compare_nominal(left, right)
    elif left.kind == "trait":
        candidate = compare_traits(left, right)
    elif left.kind == "type_alias":
        candidate = compare_type_aliases(left, right)
    else:
        return None
    if candidate is None:
        return None
    contracts = [
        ("Visibility", left.visibility, right.visibility),
        ("Attributes", left.attributes, right.attributes),
        ("Member visibility/attributes", left.metadata.get("member_contracts"), right.metadata.get("member_contracts")),
    ]
    if left.kind == "trait":
        contracts.append(("Trait bounds/header", left.signature, right.signature))
    for label, a, b in contracts:
        if a != b:
            candidate.exact = False
            candidate.divergences = [d for d in candidate.divergences if d != "No mechanical divergence found."]
            if isinstance(a, dict) and isinstance(b, dict):
                changed = {key for key in a.keys() | b.keys() if a.get(key) != b.get(key)}
                candidate.divergences.append(f"{label} differ on: {format_set(changed)}")
            else:
                candidate.divergences.append(f"{label} differ: {a} ↔ {b}")
    return candidate


def stable_hash(value: str) -> str:
    return hashlib.blake2b(value.encode("utf-8", errors="replace"), digest_size=8).hexdigest()


def abstraction_features(item: Abstraction) -> set[str]:
    features: set[str] = set()
    for name, shape in item.members.items():
        features.add("member-name:" + name)
        features.add("member-shape:" + stable_hash(shape))
        features.add("member-pair:" + stable_hash(name + "=" + shape))
    for name, signature in item.methods.items():
        features.add("method-name:" + name)
        features.add("method-shape:" + stable_hash(signature))
    for word in name_words(item.name):
        if len(word) >= 4:
            features.add("name-word:" + word)
    if item.kind in {"function", "method"}:
        shingle_hashes = {
            stable_hash("\x1f".join(shingle)) for shingle in token_shingles(item.body_tokens)
        }
        features.update("body:" + value for value in shingle_hashes)
        features.update("call:" + call for call in item.calls)
        if item.signature:
            features.add("signature:" + stable_hash(item.signature))
    if item.kind == "type_alias" and item.members.get("target"):
        target_tokens = TOKEN_RE.findall(item.members["target"])
        for shingle in token_shingles(target_tokens, size=3):
            features.add("alias:" + stable_hash("\x1f".join(shingle)))
    return features


def fallback_sort_key(item: Abstraction) -> tuple[Any, ...]:
    if item.kind in {"function", "method"}:
        return (len(item.body_tokens), len(item.signature), item.name, item.file, item.line)
    return (len(item.members), len(item.methods), item.name, item.file, item.line)


def blocked_pair_indices(
    group: Sequence[Abstraction],
    *,
    max_bucket: int = 96,
    rare_features_per_item: int = 12,
    neighbor_window: int = 18,
) -> set[tuple[int, int]]:
    """Build a bounded candidate-pair set for large item groups.

    Rare shared structural features provide recall for real near-duplicates. A local
    complexity-order window catches items with renamed members or otherwise unique
    features without reverting to quadratic comparison.
    """
    feature_sets = [abstraction_features(item) for item in group]
    frequencies = Counter(feature for features in feature_sets for feature in features)
    buckets: dict[str, list[int]] = defaultdict(list)

    for index, features in enumerate(feature_sets):
        eligible = [
            feature
            for feature in features
            if 2 <= frequencies[feature] <= max_bucket
        ]
        eligible.sort(key=lambda feature: (frequencies[feature], feature))
        for feature in eligible[:rare_features_per_item]:
            buckets[feature].append(index)

    pairs: set[tuple[int, int]] = set()
    for indices in buckets.values():
        if len(indices) < 2 or len(indices) > max_bucket:
            continue
        for left_pos, left in enumerate(indices):
            for right in indices[left_pos + 1 :]:
                pairs.add((left, right) if left < right else (right, left))

    ordered = sorted(range(len(group)), key=lambda index: fallback_sort_key(group[index]))
    position = {index: pos for pos, index in enumerate(ordered)}
    for index in range(len(group)):
        pos = position[index]
        low = max(0, pos - neighbor_window)
        high = min(len(ordered), pos + neighbor_window + 1)
        for other in ordered[low:high]:
            if other == index:
                continue
            left, right = (index, other) if index < other else (other, index)
            pairs.add((left, right))
    return pairs


def generate_candidates(
    items: Sequence[Abstraction],
    min_score: float,
    max_candidates: int,
    include_exact: bool,
) -> tuple[list[Candidate], dict[str, Any], list[dict[str, Any]]]:
    candidates: list[Candidate] = []
    stats = {
        "potential_pairs": 0,
        "pairs_considered": 0,
        "below_threshold": 0,
        "exact_omitted": 0,
        "blocked_groups": 0,
        "pairs_selected": 0,
        "pairs_prefiltered": 0,
    }
    by_kind: dict[str, list[Abstraction]] = defaultdict(list)
    for item in items:
        by_kind["callable" if item.kind in {"function", "method"} else item.kind].append(item)

    for kind, group in sorted(by_kind.items()):
        size = len(group)
        if size < 2:
            continue
        stats["potential_pairs"] += size * (size - 1) // 2
        all_pairs_limit = 700 if kind == "callable" else 500
        if size <= all_pairs_limit:
            pair_indices: Iterable[tuple[int, int]] = (
                (left, right)
                for left in range(size)
                for right in range(left + 1, size)
            )
        else:
            stats["blocked_groups"] += 1
            pair_indices = sorted(blocked_pair_indices(group))

        for left_index, right_index in pair_indices:
            left = group[left_index]
            right = group[right_index]
            stats["pairs_selected"] += 1
            if kind == "callable":
                shorter = min(len(left.body_tokens), len(right.body_tokens))
                longer = max(len(left.body_tokens), len(right.body_tokens))
                if not shorter or shorter / longer < 0.45:
                    stats["pairs_prefiltered"] += 1
                    continue
            stats["pairs_considered"] += 1
            candidate = compare_pair(left, right)
            if candidate is None or candidate.score < min_score:
                stats["below_threshold"] += 1
                continue
            if candidate.exact and not include_exact:
                stats["exact_omitted"] += 1
                continue
            candidates.append(candidate)

    candidates.sort(
        key=lambda candidate: (
            -candidate.score,
            candidate.left.file,
            candidate.left.line,
            candidate.right.file,
            candidate.right.line,
        )
    )
    emitted = []
    streams = {}
    for stream in ("types", "callables"):
        eligible = [candidate for candidate in candidates if candidate.stream == stream]
        selected = eligible[:max_candidates]
        emitted.extend(selected)
        streams[stream] = {
            "eligible": len(eligible), "emitted": len(selected),
            "truncated": len(eligible) - len(selected),
            "lowest_emitted_score": round(selected[-1].score, 4) if selected else None,
        }
    clusters = build_clusters(candidates, {candidate.stable_id for candidate in emitted})
    stats.update({
        "eligible": len(candidates), "emitted": len(emitted),
        "truncated": len(candidates) - len(emitted), "by_stream": streams,
        "pairs_not_selected": stats["potential_pairs"] - stats["pairs_selected"],
    })
    return emitted, stats, clusters


def build_clusters(candidates: Sequence[Candidate], emitted_ids: set[str]) -> list[dict[str, Any]]:
    """Connected discovery groups over all eligible edges, before output truncation."""
    parents: dict[str, str] = {}

    def find(key: str) -> str:
        parents.setdefault(key, key)
        while parents[key] != key:
            parents[key] = parents[parents[key]]
            key = parents[key]
        return key

    for candidate in candidates:
        a, b = find(candidate.left.stable_id), find(candidate.right.stable_id)
        parents[max(a, b)] = min(a, b)
    groups: dict[str, list[Candidate]] = defaultdict(list)
    for candidate in candidates:
        groups[find(candidate.left.stable_id)].append(candidate)
    result = []
    for edges in groups.values():
        members = sorted({item.stable_id for edge in edges for item in (edge.left, edge.right)})
        emitted = [edge.stable_id for edge in edges if edge.stable_id in emitted_ids]
        result.append({
            "id": "DU-GROUP-" + stable_hash("|".join(members)),
            "stream": edges[0].stream, "members": members,
            "eligible_pairs": len(edges), "candidate_ids": emitted,
            "omitted_pairs": len(edges) - len(emitted),
            "max_score": round(max(edge.score for edge in edges), 4),
        })
    return sorted(result, key=lambda group: (group["stream"], -group["max_score"], group["id"]))


def path_is_within(path: Path, root: Path) -> bool:
    try:
        path.relative_to(root)
        return True
    except ValueError:
        return False


def looks_generated(path: Path) -> bool:
    lowered = path.name.lower()
    if lowered in {"generated.rs", "bindings.rs"} or lowered.endswith((".generated.rs", "_generated.rs")):
        return True
    try:
        with path.open(encoding="utf-8", errors="ignore") as source:
            prefix = source.read(4096)
    except OSError:
        return False
    # Only leading comments can identify the file as generated. Doc prose is not a marker.
    offset = 0
    while offset < len(prefix):
        if prefix[offset].isspace():
            offset += 1
            continue
        if prefix.startswith("//", offset):
            end = prefix.find("\n", offset)
            if end == -1:
                end = len(prefix)
            is_doc = prefix.startswith(("///", "//!"), offset)
            comment = prefix[offset + 2:end]
        elif prefix.startswith("/*", offset):
            is_doc = prefix.startswith(("/**", "/*!"), offset)
            end = offset + 2
            depth = 1
            while end < len(prefix) and depth:
                if prefix.startswith("/*", end):
                    depth += 1
                    end += 2
                elif prefix.startswith("*/", end):
                    depth -= 1
                    end += 2
                else:
                    end += 1
            comment = prefix[offset + 2:end - 2 if depth == 0 else end]
        else:
            break
        if not is_doc and GENERATED_HEADER_RE.search(comment):
            return True
        offset = end
    return False


def matches_any_glob(relative: str, patterns: Sequence[str]) -> bool:
    return any(fnmatch.fnmatch(relative, pattern) or Path(relative).match(pattern) for pattern in patterns)


def iter_rust_files(
    root: Path,
    scopes: Sequence[str],
    include_tests: bool,
    include_generated: bool,
    excludes: Sequence[str],
) -> tuple[list[Path], dict[str, list[str]]]:
    root = root.resolve()
    targets: list[Path] = []
    if scopes:
        for scope in scopes:
            candidate = (root / scope).resolve()
            if not path_is_within(candidate, root):
                raise ValueError(f"Scope escapes repository root: {scope}")
            if not candidate.exists():
                raise ValueError(f"Scope does not exist: {scope}")
            targets.append(candidate)
    else:
        targets.append(root)

    files: set[Path] = set()
    skipped: dict[str, set[str]] = defaultdict(set)

    def skip(reason: str, path: Path) -> None:
        skipped[reason].add(path.relative_to(root).as_posix())

    def is_test_path(path: Path) -> bool:
        parts = path.relative_to(root).parts
        return bool(set(parts[:-1]) & TEST_PATH_SEGMENTS)

    def consider(path: Path) -> None:
        try:
            resolved = path.resolve()
        except OSError:
            skip("unreadable", path)
            return
        if not path_is_within(resolved, root):
            skip("outside_root", path)
            return
        if path.suffix != ".rs":
            return
        relative = path.relative_to(root).as_posix()
        if matches_any_glob(relative, excludes):
            skip("user_excluded", path)
            return
        if not include_tests and is_test_path(path):
            skip("test_or_example", path)
            return
        if not include_generated and looks_generated(path):
            skip("generated", path)
            return
        files.add(path)

    for target in targets:
        if target.is_file():
            consider(target)
            continue
        for dirpath, dirnames, filenames in os.walk(target):
            current = Path(dirpath)
            kept_dirs = []
            for dirname in dirnames:
                child = current / dirname
                try:
                    relative = child.relative_to(root).as_posix()
                except ValueError:
                    skip("outside_root", child)
                    continue
                if dirname in DEFAULT_EXCLUDED_DIRS or matches_any_glob(relative, excludes):
                    skip("excluded_directory", child)
                    continue
                if not include_tests and is_test_path(child / "_.rs"):
                    skip("test_or_example_directory", child)
                    continue
                kept_dirs.append(dirname)
            dirnames[:] = kept_dirs
            for filename in filenames:
                consider(current / filename)

    return sorted(files), {reason: sorted(paths) for reason, paths in sorted(skipped.items())}


def discover_manifests(root: Path, files: Sequence[Path]) -> list[str]:
    directories = {path.parent for path in files}
    manifests: set[Path] = set()
    for directory in directories:
        cursor = directory
        while path_is_within(cursor, root):
            manifest = cursor / "Cargo.toml"
            if manifest.exists():
                manifests.add(manifest)
            if cursor == root:
                break
            cursor = cursor.parent
    root_manifest = root / "Cargo.toml"
    if root_manifest.exists():
        manifests.add(root_manifest)
    return sorted(path.relative_to(root).as_posix() for path in manifests)


def cfg_requires_test(expr: str) -> bool:
    expr = expr.strip()
    if expr == "test":
        return True
    match = re.fullmatch(r"(all|any)\((.*)\)", expr, re.S)
    if not match:
        return False
    terms = [cfg_requires_test(term) for term in split_top_level(match.group(2)) if term.strip()]
    return bool(terms) and (all(terms) if match.group(1) == "any" else any(terms))


def test_only(item: RawItem) -> bool:
    cursor: Optional[RawItem] = item
    while cursor:
        for attribute in cursor.attributes:
            attribute = normalize_text(attribute)
            if re.fullmatch(r"#\[(?:(?:[\w]+::)?test|bench)(?:\(.*\))?\]", attribute):
                return True
            match = re.fullmatch(r"#\[cfg\((.*)\)\]", attribute)
            if match and cfg_requires_test(match.group(1)):
                return True
        cursor = cursor.parent
    return False


def crate_directory(path: Path, root: Path) -> Path:
    for directory in path.parents:
        if not path_is_within(directory, root):
            break
        if (directory / "Cargo.toml").is_file():
            return directory
    return root


def scan_repository(
    root: Path,
    scopes: Sequence[str],
    min_score: float,
    max_candidates: int,
    include_tests: bool,
    include_generated: bool,
    include_exact: bool,
    excludes: Sequence[str],
    details: bool = False,
) -> dict[str, Any]:
    root = root.resolve()
    rust_files, skipped = iter_rust_files(
        root=root,
        scopes=scopes,
        include_tests=include_tests,
        include_generated=include_generated,
        excludes=excludes,
    )
    if not rust_files:
        raise ValueError("No Rust source files found in the requested scope. "
                         "Test paths need --include-tests; generated files need --include-generated. "
                         f"Skipped paths: {json.dumps(skipped, sort_keys=True)}")

    abstractions: list[Abstraction] = []
    parse_errors: list[dict[str, str]] = []
    skipped_items = []
    skipped_item_count = 0
    by_crate: dict[Path, list[RawItem]] = defaultdict(list)
    for path in rust_files:
        relative = path.relative_to(root).as_posix()
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
            raw_items = parse_raw_items(text, relative)
            kept = []
            for item in raw_items:
                if not include_tests and test_only(item):
                    skipped_item_count += 1
                    if item.parent is None or not test_only(item.parent):
                        skipped_items.append({"file": relative, "line": item.line, "name": item.name, "reason": "test_attribute"})
                else:
                    kept.append(item)
            by_crate[crate_directory(path, root)].extend(kept)
        except Exception as exc:  # Discovery should continue while reporting gaps.
            parse_errors.append({"file": relative, "error": f"{type(exc).__name__}: {exc}"})

    for raw_items in by_crate.values():
        abstractions.extend(build_abstractions(raw_items))

    candidates, stats, clusters = generate_candidates(
        items=abstractions,
        min_score=min_score,
        max_candidates=max_candidates,
        include_exact=include_exact,
    )
    kind_counts = Counter(item.kind for item in abstractions)
    member_ids = {member for group in clusters for member in group["members"]}
    declarations = {}
    for item in abstractions:
        if item.stable_id in member_ids:
            summary = abstraction_summary(item)
            if not details:
                summary = {key: summary[key] for key in ("kind", "name", "file", "line", "column", "visibility", "owner")}
            declarations[item.stable_id] = summary

    return {
        "tool": {"name": "scan_rust_dup_unifier", "version": VERSION},
        "root": str(root),
        "scope": list(scopes) if scopes else ["."],
        "settings": {
            "min_score": min_score,
            "max_candidates": max_candidates,
            "include_tests": include_tests,
            "include_generated": include_generated,
            "include_exact": include_exact,
            "exclude_globs": list(excludes),
        },
        "coverage": {
            "rust_file_count": len(rust_files),
            "rust_files": [path.relative_to(root).as_posix() for path in rust_files],
            "cargo_manifests": discover_manifests(root, rust_files),
            "skipped": {reason: len(paths) for reason, paths in skipped.items()},
            "skipped_paths": skipped,
            "skipped_items": skipped_items,
            "skipped_item_count": skipped_item_count,
            "parse_errors": parse_errors,
        },
        "inventory": {
            "abstraction_count": len(abstractions),
            "by_kind": dict(sorted(kind_counts.items())),
        },
        "candidate_stats": stats,
        "declarations": declarations,
        "clusters": clusters,
        "candidates": [candidate.to_dict() for candidate in candidates],
        "warning": (
            "Heuristic similarity is discovery evidence only. Validate concept, invariants, callers, "
            "public API, serialization, ownership, trait coherence, cfg/feature behavior, unsafe contracts, "
            "and migration cost before recommending unification."
        ),
    }


def render_markdown(report: dict[str, Any]) -> str:
    coverage = report["coverage"]
    inventory = report["inventory"]
    stats = report["candidate_stats"]
    lines = [
        "# Rust Dup Unifier Candidate Scan",
        "",
        f"- Root: `{report['root']}`",
        f"- Scope: `{', '.join(report['scope'])}`",
        f"- Rust files scanned: {coverage['rust_file_count']}",
        f"- Cargo manifests observed: {len(coverage['cargo_manifests'])}",
        f"- Abstractions extracted: {inventory['abstraction_count']}",
        f"- Candidates emitted: {stats['emitted']}",
        f"- Minimum score: {report['settings']['min_score']:.2f}",
        "",
        f"> {report['warning']}",
        "",
        "## Inventory",
        "",
    ]
    if inventory["by_kind"]:
        lines.append("| Kind | Count |")
        lines.append("|---|---:|")
        for kind, count in inventory["by_kind"].items():
            lines.append(f"| `{kind}` | {count} |")
    else:
        lines.append("No abstractions were extracted.")

    lines.extend(["", "## Discovery clusters", ""])
    for group in report["clusters"]:
        lines.append(f"- `{group['id']}` ({group['stream']}): {len(group['members'])} declarations, "
                     f"{group['eligible_pairs']} eligible pairs, {group['omitted_pairs']} omitted by output cap.")
        for member in group["members"]:
            item = report["declarations"][member]
            lines.append(f"  - `{item['name']}` — `{item['file']}:{item['line']}`")
    lines.extend(["", "## Candidates", ""])
    if not report["candidates"]:
        lines.append("No candidates met the configured threshold.")
    for candidate in report["candidates"]:
        left = report["declarations"][candidate["left"]]
        right = report["declarations"][candidate["right"]]
        lines.extend(
            [
                f"### {candidate['id']} — `{left['name']}` ↔ `{right['name']}`",
                "",
                f"- Kind: `{left['kind']}`",
                f"- Score: **{candidate['score']:.2f}**",
                f"- Exact mechanical match: `{'yes' if candidate['exact'] else 'no'}`",
                f"- Left: `{left['file']}:{left['line']}`",
                f"- Right: `{right['file']}:{right['line']}`",
                f"- Signals: {', '.join(candidate['rationale'])}",
                "",
                "Divergences:",
                "",
            ]
        )
        for divergence in candidate["divergences"]:
            lines.append(f"- {divergence}")
        lines.extend(["", "Similarity signals:", ""])
        for name, value in candidate["signals"].items():
            lines.append(f"- `{name}`: {value:.0%}")
        lines.extend(
            [
                "",
                "Manual validation required: compare responsibility, invariants, callers, attributes, feature gates, and compatibility before choosing `unify`, `shared_core`, or `keep_separate`.",
                "",
            ]
        )

    lines.extend(["## Coverage Notes", ""])
    lines.append(f"Test items excluded (including descendants): {coverage['skipped_item_count']}")
    lines.append(f"Pairs compared: {stats['pairs_considered']} of {stats['potential_pairs']}; "
                 f"sampled groups: {stats['blocked_groups']}; pairs not selected: {stats['pairs_not_selected']}; "
                 f"length-prefiltered: {stats['pairs_prefiltered']}.")
    lines.append(f"Output truncation: {stats['truncated']} eligible pairs omitted (cap per stream).")
    for stream, counts in stats["by_stream"].items():
        lines.append(f"- {stream}: {counts['emitted']}/{counts['eligible']} emitted; "
                     f"lowest emitted score: {counts['lowest_emitted_score']}")
    for reason, paths in coverage["skipped_paths"].items():
        lines.append(f"- {reason}: " + ", ".join(f"`{path}`" for path in paths))
    for item in coverage["skipped_items"]:
        lines.append(f"- Test item skipped: `{item['file']}:{item['line']}` ({item['name']})")
    lines.append("")
    if coverage["cargo_manifests"]:
        lines.append("Cargo manifests: " + ", ".join(f"`{item}`" for item in coverage["cargo_manifests"]))
        lines.append("")
    if coverage["skipped"]:
        lines.append("Skipped paths/files by reason:")
        lines.append("")
        for reason, count in coverage["skipped"].items():
            lines.append(f"- `{reason}`: {count}")
        lines.append("")
    if coverage["parse_errors"]:
        lines.append("Parse gaps:")
        lines.append("")
        for error in coverage["parse_errors"]:
            lines.append(f"- `{error['file']}` — {error['error']}")
        lines.append("")
    if stats.get("exact_omitted"):
        lines.append(f"Mechanically exact candidates omitted: {stats['exact_omitted']} (remove `--exclude-exact` to emit them).")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def write_output(content: str, output: Optional[str]) -> None:
    if output:
        destination = Path(output)
        destination.parent.mkdir(parents=True, exist_ok=True)
        temp = destination.with_suffix(destination.suffix + ".tmp")
        temp.write_text(content, encoding="utf-8")
        temp.replace(destination)
    else:
        sys.stdout.write(content)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Find structurally or behaviorally similar Rust abstractions that deserve manual "
            "duplication/unification review."
        )
    )
    parser.add_argument("root", nargs="?", default=".", help="Rust repository root (default: current directory)")
    parser.add_argument(
        "--scope",
        action="append",
        default=[],
        metavar="PATH",
        help="Repository-relative file or directory to scan; repeatable",
    )
    parser.add_argument("--min-score", type=float, default=0.68, help="Candidate threshold from 0 to 1")
    parser.add_argument("--max-candidates", type=int, default=100, help="Maximum pairs per stream (types and callables each get this budget)")
    parser.add_argument("--include-tests", action="store_true", help="Include tests, examples, benches, and fixtures")
    parser.add_argument("--include-generated", action="store_true", help="Include generated-looking Rust files")
    exact = parser.add_mutually_exclusive_group()
    exact.add_argument("--include-exact", dest="include_exact", action="store_true", default=True,
                       help="Include mechanically exact matches (default)")
    exact.add_argument("--exclude-exact", dest="include_exact", action="store_false", help="Omit mechanically exact matches")
    parser.add_argument("--details", action="store_true", help="Include full declaration shapes in JSON")
    parser.add_argument(
        "--exclude",
        action="append",
        default=[],
        metavar="GLOB",
        help="Additional repository-relative exclusion glob; repeatable",
    )
    parser.add_argument("--format", choices=("markdown", "json"), default="markdown")
    parser.add_argument("--output", "-o", help="Write output to a file instead of stdout")
    parser.add_argument("--version", action="version", version=f"%(prog)s {VERSION}")
    return parser


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    if not (0.0 <= args.min_score <= 1.0):
        parser.error("--min-score must be between 0 and 1")
    if args.max_candidates < 1:
        parser.error("--max-candidates must be at least 1")

    root = Path(args.root)
    if not root.exists() or not root.is_dir():
        parser.error(f"repository root is not a directory: {root}")

    try:
        report = scan_repository(
            root=root,
            scopes=args.scope,
            min_score=args.min_score,
            max_candidates=args.max_candidates,
            include_tests=args.include_tests,
            include_generated=args.include_generated,
            include_exact=args.include_exact,
            excludes=args.exclude,
            details=args.details,
        )
    except ValueError as exc:
        parser.error(str(exc))

    if args.format == "json":
        content = json.dumps(report, indent=2, sort_keys=True) + "\n"
    else:
        content = render_markdown(report)
    write_output(content, args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
